### PR TITLE
Added Watch tool reference to .fsproj

### PR DESCRIPTION
**Pull request by spaasis**
I couldn't get the watch working in my environment without this. Maybe this would help others as well?

### CODE REVIEW

**Comment by isaacabraham** [comment]
Hey. I think this is just because your version of .NET Core needs an upgrade. The earlier versions didn't have an integrated watch tool and you needed the separate tool. In newer versions it's integrated into the CLI. So you should be able to upgrade core on your machine and it'll just work.

If you can confirm this, I'll close this PR.

Thanks!!

**Comment by spaasis** [comment]
Very likely that it's something like that. However, it seems like I'm running the latest .NET Core. Can you spot anything odd from this (dotnet --info): .NET Core SDK (reflecting any global.json):
```
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     antergos
 OS Version:
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /opt/dotnet/sdk/2.2.102/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.102 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 2.2.1 [/opt/dotnet/shared/Microsoft.NETCore.App]
```

My Mono is at 5.16.

The error without this config is 
```
Cannot find command 'dotnet watch', please run the following command to install

dotnet tool install --global dotnet-watch
```
I've ran the command, and it installs ok, but still doesn't do much.

I also seems to have a build issue (on dotnet build) so romething is probably pretty borked at my configuration somewhere.

I'll close this since I believe that this is not an issue with the code itself.

**Comment by spaasis** [comment]
Whew, got it working. Here's my steps for anyone running into the same issues (probably due to the Arch dotnet package)
Added this to .bashrc (edit: removed extra line that didn't actually matter)
`export PATH="$PATH:/home/<user>/.dotnet/tools"`

`dotnet tool install --global dotnet-watch`

That got the dotnet watch working. 
Next was the build error, which got solved by this:
https://github.com/Microsoft/visualfsharp/issues/3303 

Now I can get to actually start the Dojo.
Cheers!

**Comment by isaacabraham** [comment]
Wow. Thanks for figuring this out. @bruinbrown thoughts?

**Pull request closed without merging**
