### PR TITLE
Update SAFE Dojo to use latest version of template

### PR DESCRIPTION
**Pull request by bruinbrown**
This uses the latest version of the SAFE template 0.38.2 which updates Fable, Fulma and Saturn as well as the Webpack config.

ToDo:
- [x] Update the instructions
- [x] Create encoders for Thoth Json

### CODE REVIEW

**Comment by keyset** [comment]
Installing FAKE 5 as a global tool should be added to the prerequisites.

**Comment by bruinbrown** [comment]
@isaacabraham I think this is good to merge in now, can you give it a quick shufties? If it looks alright I’ll merge it in

**Comment by isaacabraham** [comment]
@bruinbrown out of interest, what effort was involved to "upgrade" the project to the latest template?

**Comment by bruinbrown** [comment]
@isaacabraham The main changes were relating to the way everything is built using npm and so needed a change to the build script which I ended up just copying from a ``dotnet new safe``. It also needed some changes to the way env vars are retrieved based on what @keyset found with FAKE 5. And some minor changes to the way the JS dependency option works.

There was also the need to upgrade versions in NPM and Paket to match the versions in a version of the SAFE template.

I needed to change the way FontAwesome icons were used on the Fable side.

There were a couple of changes within the code where member names had changed as well

Since the build process was the hardest part, I ended up actually just doing a ``dotnet new safe`` and copying over the code files themselves

**Comment by isaacabraham** [comment]
Might it be worth adding a set "upgrading" instructions onto the main safe docs site?

**Comment by isaacabraham** [comment]
@bruinbrown what about the suggested solution branch by the way?

**Comment by isaacabraham** [comment]
@bruinbrown F5 doesn't seem to work in Code i.e. `tasks.json` and `launch.json` aren't set up correctly (or the fake script needs updating).

**Comment by isaacabraham** [comment]
LGTM - if you want to get F5 working that'll be great.

**Pull request merged**
